name: gestion_chantier
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  dotted_border: ^3.1.0
  fl_chart: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  pie_chart: ^5.4.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  file_picker: ^8.0.0+1
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  flutter_switch: ^0.3.2
  url_launcher: ^6.3.2
  geolocator: ^13.0.1
  qr_code_scanner: ^1.0.1
  change_app_package_name: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

  # images
    - assets/images/img.png
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/avatar1.png 
    - assets/images/avatar2.png 
    - assets/images/avatar3.png
    - assets/images/bg.png
    - assets/images/profil.jpg
    

  #   icons
    - assets/icons/image.svg
    - assets/icons/check.svg
    - assets/icons/home.svg
    - assets/icons/home_selected.svg
    - assets/icons/user.svg
    - assets/icons/user_selected.svg
    - assets/icons/doc.svg
    - assets/icons/doc_selected.svg
    - assets/icons/user-edit.svg
    - assets/icons/alert.svg
    - assets/icons/alert_selected.svg
    - assets/icons/stock.svg
    - assets/icons/stock_selected.svg
    - assets/icons/docs.svg
    - assets/icons/docs_selected.svg
    - assets/icons/plus.svg
    - assets/icons/chart.svg
    - assets/icons/hom.svg
    - assets/icons/friend.svg
    - assets/icons/money.svg    
    - assets/icons/stat.svg
    - assets/icons/com.svg
    - assets/icons/box.svg
    - assets/icons/bus.svg
    - assets/icons/calendar.svg
    - assets/icons/x.svg
    - assets/icons/p.svg
    - assets/icons/w.svg
    - assets/icons/warning.svg
    - assets/icons/sack.svg
    - assets/icons/qr.svg
    - assets/icons/checks.svg
    - assets/icons/checks_selected.svg
    - assets/icons/qr_selected.svg
    - assets/icons/lock.svg
    - assets/icons/notifs.svg
    - assets/icons/edit.svg
    - assets/icons/logout.svg
    - assets/icons/bulletin.svg
    - assets/icons/entrer.svg
    - assets/icons/sortie.svg
    
   




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
